Added enableObjectStream option
expressjs/morgan pull request #194
Opened 2019-05-07 22:24 UTC by SnakeA

## Background 

I've got a similar use case with the issue raised: https://github.com/expressjs/morgan/issues/181. 

I am using Morgan for a lot of my projects and I would like to be able to write an Object in a stream instead of just a string.

Reason is that I am using Winston which supports meta-data for reach-er logs. I would like to use morgan and pass an object to Winston - instead of parsing a string. 

## Changes
- Added a **backwards compatible** `enableObjectStream` in morgan() call. 
 - Defaults to false
- It needs a custom format function and a defined stream to work.
- The only diff is that if the above are true (`customFormatFunction && stream && enableObjectStream`), we are not concatenating a `\n` (newline char), hence morgan can stream an object.

Any improvements/changes are welcome.

2019-05-10 15:13 UTC, SnakeA commented
@dougwilson  Could you please have a look 😄  Thanks !

2019-05-10 15:17 UTC, dougwilson commented
I will after the express 4.17 release is out, as there was a premature vulnerability listed and it is our number 1 priority right now, I hope you understand.

2019-05-10 15:50 UTC, SnakeA commented
@dougwilson 
Thank you for getting back to me 😄 No worries I do understand that you have other priorities 

I did some digging and I've realised that a lot of people tried to make this change to Morgan but it never went out. 

Morgan is being used by numerous of our project and does the job, other than the fact that it emits a string that we have to parse. 

It would be great if we can work something out, otherwise, we might have to implement our own middleware 

Thanks again and looking forward to your review & opinion

2019-05-23 12:23 UTC, SnakeA commented
@dougwilson 

Any updates? 
I can see that express 4.17 was released last week? 

Thanks!

2019-05-23 13:14 UTC, dougwilson requested changes
Sorry, still getting reports about 4.17 from users. Here is a very quick review for points to work on:

1. No docs for new feature in pr
2. Does not work right when buffer feature enabled
3. Silently does nothing when using built in formatters. It could throw an error or at least be documented. 

I hope this feedback helps while I am working on 4.17 issues in parallel.

2026-09-09 13:37 UTC, UlisesGascon commented
Thanks for opening this, @SnakeA, and sorry it sat for so long. Closing it now because the use case has been addressed on master by #375.

Rather than a new option, morgan now checks the stream's own `writableObjectMode` flag. When it is `true` and a custom format function returns an object, the object is written to the stream as is, with no newline appended. String formats keep producing strings, so nothing changes for existing users.

Example:

```js
var stream = new Writable({
  writableObjectMode: true,
  write: function (obj, encoding, callback) {
    logger.info('request', obj)
    callback()
  }
})

app.use(morgan(function (tokens, req, res) {
  return { method: tokens.method(req, res), url: tokens.url(req, res), status: tokens.status(req, res) }
}, { stream: stream }))
```

2026-09-09 13:37 UTC, closed without merging